"""billing ledger and pricing

Revision ID: 062d208453a8
Revises: 2cb3756ebf43
Create Date: 2026-08-17 01:38:09.930140

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '062d208453a8'
down_revision: str | None = '2cb3756ebf43'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credit_accounts',
    sa.Column('resource_type', sa.String(length=16), nullable=False),
    sa.Column('balance', sa.BigInteger(), nullable=False),
    sa.Column('reserved', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('balance >= 0', name=op.f('ck_credit_accounts_balance_non_negative')),
    sa.CheckConstraint('reserved >= 0', name=op.f('ck_credit_accounts_reserved_non_negative')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_credit_accounts')),
    sa.UniqueConstraint('org_id', 'resource_type', name='uq_credit_accounts_org_resource')
    )
    op.create_index(op.f('ix_credit_accounts_deleted_at'), 'credit_accounts', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_credit_accounts_org_id'), 'credit_accounts', ['org_id'], unique=False)
    op.create_table('model_pricing',
    sa.Column('model_id', sa.String(length=64), nullable=False),
    sa.Column('unit', sa.String(length=16), nullable=False),
    sa.Column('provider_cost', sa.BigInteger(), nullable=False),
    sa.Column('credit_price', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_model_pricing'))
    )
    op.create_index(op.f('ix_model_pricing_deleted_at'), 'model_pricing', ['deleted_at'], unique=False)
    op.create_index('ix_model_pricing_model', 'model_pricing', ['model_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_model_pricing_model_id'), 'model_pricing', ['model_id'], unique=False)
    op.create_table('pricing_rules',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.BigInteger(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pricing_rules')),
    sa.UniqueConstraint('key', name=op.f('uq_pricing_rules_key'))
    )
    op.create_index(op.f('ix_pricing_rules_deleted_at'), 'pricing_rules', ['deleted_at'], unique=False)
    op.create_table('credit_transactions',
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('reserved_delta', sa.BigInteger(), nullable=False),
    sa.Column('balance_after', sa.BigInteger(), nullable=False),
    sa.Column('reserved_after', sa.BigInteger(), nullable=False),
    sa.Column('is_bonus', sa.Boolean(), nullable=False),
    sa.Column('ref_type', sa.String(length=24), nullable=True),
    sa.Column('ref_id', sa.Uuid(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=160), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['credit_accounts.id'], name=op.f('fk_credit_transactions_account_id_credit_accounts'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_credit_transactions')),
    sa.UniqueConstraint('idempotency_key', name=op.f('uq_credit_transactions_idempotency_key'))
    )
    op.create_index(op.f('ix_credit_transactions_account_id'), 'credit_transactions', ['account_id'], unique=False)
    op.create_index(op.f('ix_credit_transactions_deleted_at'), 'credit_transactions', ['deleted_at'], unique=False)
    op.create_index('ix_credit_tx_account_created', 'credit_transactions', ['account_id', 'created_at'], unique=False)
    op.create_index('ix_credit_tx_ref', 'credit_transactions', ['ref_type', 'ref_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # 每个 migration 必须可回滚且经过测试（09_Database.md 第 14 节）
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_credit_tx_ref', table_name='credit_transactions')
    op.drop_index('ix_credit_tx_account_created', table_name='credit_transactions')
    op.drop_index(op.f('ix_credit_transactions_deleted_at'), table_name='credit_transactions')
    op.drop_index(op.f('ix_credit_transactions_account_id'), table_name='credit_transactions')
    op.drop_table('credit_transactions')
    op.drop_index(op.f('ix_pricing_rules_deleted_at'), table_name='pricing_rules')
    op.drop_table('pricing_rules')
    op.drop_index(op.f('ix_model_pricing_model_id'), table_name='model_pricing')
    op.drop_index('ix_model_pricing_model', table_name='model_pricing')
    op.drop_index(op.f('ix_model_pricing_deleted_at'), table_name='model_pricing')
    op.drop_table('model_pricing')
    op.drop_index(op.f('ix_credit_accounts_org_id'), table_name='credit_accounts')
    op.drop_index(op.f('ix_credit_accounts_deleted_at'), table_name='credit_accounts')
    op.drop_table('credit_accounts')
    # ### end Alembic commands ###
