"""consistency engine tables

Revision ID: 22dbb7fcecbc
Revises: 9d524d4863e9
Create Date: 2026-08-17 02:54:14.485838

"""
from __future__ import annotations

from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql
revision: str = '22dbb7fcecbc'
down_revision: str | None = '9d524d4863e9'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('character_profiles',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('ref', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('appearance_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('base_portrait_asset_id', sa.Uuid(), nullable=True),
    sa.Column('turnaround_asset_ids', postgresql.ARRAY(sa.Uuid()), nullable=False),
    sa.Column('consistency_tier', sa.String(length=4), nullable=False),
    sa.Column('reference_embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_character_profiles'))
    )
    op.create_index(op.f('ix_character_profiles_deleted_at'), 'character_profiles', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_character_profiles_org_id'), 'character_profiles', ['org_id'], unique=False)
    op.create_index(op.f('ix_character_profiles_project_id'), 'character_profiles', ['project_id'], unique=False)
    op.create_index('ix_character_profiles_project_ref', 'character_profiles', ['project_id', 'ref', 'version'], unique=False)
    op.create_table('shot_conditioning',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('shot_index', sa.Integer(), nullable=False),
    sa.Column('style_profile_id', sa.Uuid(), nullable=True),
    sa.Column('character_profile_ids', postgresql.ARRAY(sa.Uuid()), nullable=False),
    sa.Column('resolved_prompt', sa.Text(), nullable=False),
    sa.Column('negative_prompt', sa.Text(), nullable=False),
    sa.Column('seed', sa.Integer(), nullable=True),
    sa.Column('asset_id', sa.Uuid(), nullable=True),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('accepted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shot_conditioning'))
    )
    op.create_index(op.f('ix_shot_conditioning_deleted_at'), 'shot_conditioning', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_shot_conditioning_org_id'), 'shot_conditioning', ['org_id'], unique=False)
    op.create_index(op.f('ix_shot_conditioning_project_id'), 'shot_conditioning', ['project_id'], unique=False)
    op.create_index('ix_shot_conditioning_project_shot', 'shot_conditioning', ['project_id', 'shot_index', 'attempt'], unique=False)
    op.create_table('shot_quality_scores',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('shot_index', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Uuid(), nullable=True),
    sa.Column('metric', sa.String(length=40), nullable=False),
    sa.Column('value', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('threshold', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shot_quality_scores'))
    )
    op.create_index('ix_shot_quality_project_shot', 'shot_quality_scores', ['project_id', 'shot_index', 'metric'], unique=False)
    op.create_index(op.f('ix_shot_quality_scores_deleted_at'), 'shot_quality_scores', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_shot_quality_scores_org_id'), 'shot_quality_scores', ['org_id'], unique=False)
    op.create_index(op.f('ix_shot_quality_scores_project_id'), 'shot_quality_scores', ['project_id'], unique=False)
    op.create_table('style_profiles',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('base_model', sa.String(length=64), nullable=False),
    sa.Column('positive_tokens', sa.Text(), nullable=False),
    sa.Column('negative_tokens', sa.Text(), nullable=False),
    sa.Column('color_grading', sa.String(length=120), nullable=False),
    sa.Column('line_weight', sa.String(length=40), nullable=False),
    sa.Column('render_mode', sa.String(length=40), nullable=False),
    sa.Column('seed_base', sa.Integer(), nullable=False),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_style_profiles'))
    )
    op.create_index(op.f('ix_style_profiles_deleted_at'), 'style_profiles', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_style_profiles_org_id'), 'style_profiles', ['org_id'], unique=False)
    op.create_index(op.f('ix_style_profiles_project_id'), 'style_profiles', ['project_id'], unique=False)
    op.create_index('ix_style_profiles_project_version', 'style_profiles', ['project_id', 'version'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # 每个 migration 必须可回滚且经过测试（09_Database.md 第 14 节）
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_style_profiles_project_version', table_name='style_profiles')
    op.drop_index(op.f('ix_style_profiles_project_id'), table_name='style_profiles')
    op.drop_index(op.f('ix_style_profiles_org_id'), table_name='style_profiles')
    op.drop_index(op.f('ix_style_profiles_deleted_at'), table_name='style_profiles')
    op.drop_table('style_profiles')
    op.drop_index(op.f('ix_shot_quality_scores_project_id'), table_name='shot_quality_scores')
    op.drop_index(op.f('ix_shot_quality_scores_org_id'), table_name='shot_quality_scores')
    op.drop_index(op.f('ix_shot_quality_scores_deleted_at'), table_name='shot_quality_scores')
    op.drop_index('ix_shot_quality_project_shot', table_name='shot_quality_scores')
    op.drop_table('shot_quality_scores')
    op.drop_index('ix_shot_conditioning_project_shot', table_name='shot_conditioning')
    op.drop_index(op.f('ix_shot_conditioning_project_id'), table_name='shot_conditioning')
    op.drop_index(op.f('ix_shot_conditioning_org_id'), table_name='shot_conditioning')
    op.drop_index(op.f('ix_shot_conditioning_deleted_at'), table_name='shot_conditioning')
    op.drop_table('shot_conditioning')
    op.drop_index('ix_character_profiles_project_ref', table_name='character_profiles')
    op.drop_index(op.f('ix_character_profiles_project_id'), table_name='character_profiles')
    op.drop_index(op.f('ix_character_profiles_org_id'), table_name='character_profiles')
    op.drop_index(op.f('ix_character_profiles_deleted_at'), table_name='character_profiles')
    op.drop_table('character_profiles')
    # ### end Alembic commands ###
