"""tasks and outbox

Revision ID: 2cb3756ebf43
Revises: 440893368453
Create Date: 2026-08-16 17:50:59.138700

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql
revision: str = '2cb3756ebf43'
down_revision: str | None = '440893368453'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # 手工补充：Alembic 的 autogenerate 不会为独立 Sequence 生成 CREATE SEQUENCE，
    # 只会在列上引用 nextval()。少了这一句建表就会失败。
    op.execute("CREATE SEQUENCE IF NOT EXISTS outbox_events_seq")

    op.create_table('outbox_events',
    sa.Column('seq', sa.BigInteger(), server_default=sa.text("nextval('outbox_events_seq')"), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.Column('type', sa.String(length=48), nullable=False),
    sa.Column('data_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_outbox_events')),
    sa.UniqueConstraint('seq', name=op.f('uq_outbox_events_seq'))
    )
    op.create_index(op.f('ix_outbox_events_deleted_at'), 'outbox_events', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_outbox_events_org_id'), 'outbox_events', ['org_id'], unique=False)
    op.create_index(op.f('ix_outbox_events_project_id'), 'outbox_events', ['project_id'], unique=False)
    op.create_index('ix_outbox_pending', 'outbox_events', ['seq'], unique=False, postgresql_where=sa.text('published_at IS NULL'))
    op.create_table('tasks',
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('type', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.String(length=64), nullable=True),
    sa.Column('model_id', sa.String(length=64), nullable=True),
    sa.Column('input_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('output_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('estimated_cost', sa.BigInteger(), nullable=False),
    sa.Column('reserved_cost', sa.BigInteger(), nullable=False),
    sa.Column('actual_cost', sa.BigInteger(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=True),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.Column('counts_as_waste', sa.Boolean(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tasks')),
    sa.UniqueConstraint('idempotency_key', name=op.f('uq_tasks_idempotency_key'))
    )
    op.create_index('ix_tasks_created_at', 'tasks', ['created_at'], unique=False)
    op.create_index(op.f('ix_tasks_deleted_at'), 'tasks', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_tasks_org_id'), 'tasks', ['org_id'], unique=False)
    op.create_index('ix_tasks_org_project_created', 'tasks', ['org_id', 'project_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_tasks_project_id'), 'tasks', ['project_id'], unique=False)
    op.create_index('ix_tasks_status_priority', 'tasks', ['status', 'priority', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # 每个 migration 必须可回滚且经过测试（09_Database.md 第 14 节）
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tasks_status_priority', table_name='tasks')
    op.drop_index(op.f('ix_tasks_project_id'), table_name='tasks')
    op.drop_index('ix_tasks_org_project_created', table_name='tasks')
    op.drop_index(op.f('ix_tasks_org_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_deleted_at'), table_name='tasks')
    op.drop_index('ix_tasks_created_at', table_name='tasks')
    op.drop_table('tasks')
    op.drop_index('ix_outbox_pending', table_name='outbox_events', postgresql_where=sa.text('published_at IS NULL'))
    op.drop_index(op.f('ix_outbox_events_project_id'), table_name='outbox_events')
    op.drop_index(op.f('ix_outbox_events_org_id'), table_name='outbox_events')
    op.drop_index(op.f('ix_outbox_events_deleted_at'), table_name='outbox_events')
    op.drop_table('outbox_events')
    # 同上，序列也要手工回收，否则回滚后重跑会撞上残留的序列
    op.execute("DROP SEQUENCE IF EXISTS outbox_events_seq")
