"""agent runs steps approvals

Revision ID: 3df43da2941d
Revises: 062d208453a8
Create Date: 2026-08-17 02:10:44.747405

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql
revision: str = '3df43da2941d'
down_revision: str | None = '062d208453a8'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_runs',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('agent_id', sa.String(length=80), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('input_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('output_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('model_id', sa.String(length=64), nullable=True),
    sa.Column('tokens_in', sa.Integer(), nullable=False),
    sa.Column('tokens_out', sa.Integer(), nullable=False),
    sa.Column('cost', sa.BigInteger(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_runs'))
    )
    op.create_index(op.f('ix_agent_runs_deleted_at'), 'agent_runs', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_agent_runs_org_id'), 'agent_runs', ['org_id'], unique=False)
    op.create_index('ix_agent_runs_project_created', 'agent_runs', ['project_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_agent_runs_project_id'), 'agent_runs', ['project_id'], unique=False)
    op.create_table('agent_steps',
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('step_index', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('resolved_prompt', sa.Text(), nullable=True),
    sa.Column('raw_output', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_steps'))
    )
    op.create_index(op.f('ix_agent_steps_deleted_at'), 'agent_steps', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_agent_steps_org_id'), 'agent_steps', ['org_id'], unique=False)
    op.create_index(op.f('ix_agent_steps_run_id'), 'agent_steps', ['run_id'], unique=False)
    op.create_index('ix_agent_steps_run_index', 'agent_steps', ['run_id', 'step_index'], unique=False)
    op.create_table('approvals',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('gate', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('payload_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_approvals'))
    )
    op.create_index(op.f('ix_approvals_deleted_at'), 'approvals', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_approvals_org_id'), 'approvals', ['org_id'], unique=False)
    op.create_index('ix_approvals_project_created', 'approvals', ['project_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_approvals_project_id'), 'approvals', ['project_id'], unique=False)
    op.create_index('uq_approvals_pending_gate', 'approvals', ['project_id', 'gate'], unique=True, postgresql_where=sa.text("status IN ('pending')"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # 每个 migration 必须可回滚且经过测试（09_Database.md 第 14 节）
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_approvals_pending_gate', table_name='approvals', postgresql_where=sa.text("status IN ('pending')"))
    op.drop_index(op.f('ix_approvals_project_id'), table_name='approvals')
    op.drop_index('ix_approvals_project_created', table_name='approvals')
    op.drop_index(op.f('ix_approvals_org_id'), table_name='approvals')
    op.drop_index(op.f('ix_approvals_deleted_at'), table_name='approvals')
    op.drop_table('approvals')
    op.drop_index('ix_agent_steps_run_index', table_name='agent_steps')
    op.drop_index(op.f('ix_agent_steps_run_id'), table_name='agent_steps')
    op.drop_index(op.f('ix_agent_steps_org_id'), table_name='agent_steps')
    op.drop_index(op.f('ix_agent_steps_deleted_at'), table_name='agent_steps')
    op.drop_table('agent_steps')
    op.drop_index(op.f('ix_agent_runs_project_id'), table_name='agent_runs')
    op.drop_index('ix_agent_runs_project_created', table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_org_id'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_deleted_at'), table_name='agent_runs')
    op.drop_table('agent_runs')
    # ### end Alembic commands ###
