"""conversation messages

Revision ID: 62c955d6f428
Revises: 22dbb7fcecbc
Create Date: 2026-08-17 15:49:58.153506

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql
revision: str = '62c955d6f428'
down_revision: str | None = '22dbb7fcecbc'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation_messages',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('target_role', sa.String(length=16), nullable=False),
    sa.Column('author', sa.String(length=16), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=True),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('changed_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conversation_messages'))
    )
    op.create_index(op.f('ix_conversation_messages_deleted_at'), 'conversation_messages', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_conversation_messages_org_id'), 'conversation_messages', ['org_id'], unique=False)
    op.create_index(op.f('ix_conversation_messages_project_id'), 'conversation_messages', ['project_id'], unique=False)
    op.create_index('ix_conversation_project_created', 'conversation_messages', ['project_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # 每个 migration 必须可回滚且经过测试（09_Database.md 第 14 节）
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_conversation_project_created', table_name='conversation_messages')
    op.drop_index(op.f('ix_conversation_messages_project_id'), table_name='conversation_messages')
    op.drop_index(op.f('ix_conversation_messages_org_id'), table_name='conversation_messages')
    op.drop_index(op.f('ix_conversation_messages_deleted_at'), table_name='conversation_messages')
    op.drop_table('conversation_messages')
    # ### end Alembic commands ###
