"""byok credentials, org skills, project skill/model preference

ADR-024/025/026 的数据层。全部是新增：两张新表 + projects 两个可空列，
不改动任何已有列，存量行不需要回填。

Revision ID: 68068f1faa9c
Revises: a1f3c07b52d4
Create Date: 2026-08-18 15:17:51.740305

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql
revision: str = '68068f1faa9c'
down_revision: str | None = 'a1f3c07b52d4'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('org_skills',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('spec_yaml', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=8), nullable=False),
    sa.Column('validation_errors', sa.Text(), nullable=True),
    sa.Column('uploaded_by', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_org_skills'))
    )
    op.create_index(op.f('ix_org_skills_deleted_at'), 'org_skills', ['deleted_at'], unique=False)
    op.create_index('ix_org_skills_org_created', 'org_skills', ['org_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_org_skills_org_id'), 'org_skills', ['org_id'], unique=False)
    op.create_table('provider_credentials',
    sa.Column('capability', sa.String(length=32), nullable=False),
    sa.Column('provider_id', sa.String(length=32), nullable=False),
    sa.Column('key_encrypted', sa.Text(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_provider_credentials')),
    sa.UniqueConstraint('org_id', 'capability', name='uq_provider_credentials_org_capability')
    )
    op.create_index(op.f('ix_provider_credentials_deleted_at'), 'provider_credentials', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_provider_credentials_org_id'), 'provider_credentials', ['org_id'], unique=False)
    op.add_column('projects', sa.Column('selected_skill_id', sa.Uuid(), nullable=True))
    op.add_column('projects', sa.Column('model_preference', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.create_index(op.f('ix_projects_selected_skill_id'), 'projects', ['selected_skill_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # 每个 migration 必须可回滚且经过测试（09_Database.md 第 14 节）
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_projects_selected_skill_id'), table_name='projects')
    op.drop_column('projects', 'model_preference')
    op.drop_column('projects', 'selected_skill_id')
    op.drop_index(op.f('ix_provider_credentials_org_id'), table_name='provider_credentials')
    op.drop_index(op.f('ix_provider_credentials_deleted_at'), table_name='provider_credentials')
    op.drop_table('provider_credentials')
    op.drop_index(op.f('ix_org_skills_org_id'), table_name='org_skills')
    op.drop_index('ix_org_skills_org_created', table_name='org_skills')
    op.drop_index(op.f('ix_org_skills_deleted_at'), table_name='org_skills')
    op.drop_table('org_skills')
    # ### end Alembic commands ###
