"""asset folders and standalone character entries

三张新表，一列现有表都没动（ADR-028）：

    asset_folders        用户自建的分类，属于用户不属于项目
    asset_folder_items   归类关系。独立一张表而不是给 assets 加 folder_id——
                         要归类的还有角色/场景档案，那在 agent 模块的表上，
                         asset 模块不能往别人的表上加列（ADR-009）
    character_entries    一段参考描述直接生成的角色档案，不挂任何项目。
                         没有复用 agent_runs：那张表的 project_id 是 NOT NULL，
                         而它被"按项目查档案"的代码四处依赖，为一个新入口
                         去松这条约束风险太大

`uq_asset_folders_owner_name` 是**带 deleted_at IS NULL 的部分唯一索引**，
不是普通唯一约束：删掉"参考图"之后必须能再建一个同名的，
而普通唯一约束看不见软删标记。

Revision ID: c432be4bec40
Revises: 68068f1faa9c
Create Date: 2026-08-19 04:04:10.227427

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql
revision: str = 'c432be4bec40'
down_revision: str | None = '68068f1faa9c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset_folder_items',
    sa.Column('folder_id', sa.Uuid(), nullable=False),
    sa.Column('owner_user_id', sa.Uuid(), nullable=False),
    sa.Column('item_type', sa.String(length=16), nullable=False),
    sa.Column('item_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_asset_folder_items')),
    sa.UniqueConstraint('org_id', 'item_type', 'item_id', name='uq_folder_items_item')
    )
    op.create_index(op.f('ix_asset_folder_items_deleted_at'), 'asset_folder_items', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_asset_folder_items_org_id'), 'asset_folder_items', ['org_id'], unique=False)
    op.create_index('ix_folder_items_folder', 'asset_folder_items', ['org_id', 'folder_id'], unique=False)
    op.create_index('ix_folder_items_owner', 'asset_folder_items', ['org_id', 'owner_user_id'], unique=False)
    op.create_table('asset_folders',
    sa.Column('owner_user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_asset_folders'))
    )
    op.create_index(op.f('ix_asset_folders_deleted_at'), 'asset_folders', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_asset_folders_org_id'), 'asset_folders', ['org_id'], unique=False)
    op.create_index('ix_asset_folders_org_owner_created', 'asset_folders', ['org_id', 'owner_user_id', 'created_at'], unique=False)
    op.create_index('uq_asset_folders_owner_name', 'asset_folders', ['org_id', 'owner_user_id', 'name'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('character_entries',
    sa.Column('owner_user_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('source_text', sa.Text(), nullable=False),
    sa.Column('agent_id', sa.String(length=80), nullable=False),
    sa.Column('output_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('resolved_prompt', sa.Text(), nullable=True),
    sa.Column('model_id', sa.String(length=64), nullable=True),
    sa.Column('tokens_in', sa.Integer(), nullable=False),
    sa.Column('tokens_out', sa.Integer(), nullable=False),
    sa.Column('cost', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_character_entries'))
    )
    op.create_index(op.f('ix_character_entries_deleted_at'), 'character_entries', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_character_entries_org_id'), 'character_entries', ['org_id'], unique=False)
    op.create_index('ix_character_entries_org_owner_created', 'character_entries', ['org_id', 'owner_user_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # 每个 migration 必须可回滚且经过测试（09_Database.md 第 14 节）
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_character_entries_org_owner_created', table_name='character_entries')
    op.drop_index(op.f('ix_character_entries_org_id'), table_name='character_entries')
    op.drop_index(op.f('ix_character_entries_deleted_at'), table_name='character_entries')
    op.drop_table('character_entries')
    op.drop_index('uq_asset_folders_owner_name', table_name='asset_folders', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('ix_asset_folders_org_owner_created', table_name='asset_folders')
    op.drop_index(op.f('ix_asset_folders_org_id'), table_name='asset_folders')
    op.drop_index(op.f('ix_asset_folders_deleted_at'), table_name='asset_folders')
    op.drop_table('asset_folders')
    op.drop_index('ix_folder_items_owner', table_name='asset_folder_items')
    op.drop_index('ix_folder_items_folder', table_name='asset_folder_items')
    op.drop_index(op.f('ix_asset_folder_items_org_id'), table_name='asset_folder_items')
    op.drop_index(op.f('ix_asset_folder_items_deleted_at'), table_name='asset_folder_items')
    op.drop_table('asset_folder_items')
    # ### end Alembic commands ###
