"use client";
import Link from "next/link";
import { usePathname } from "next/navigation";
import { ChevronLeft, MoreHorizontal } from "lucide-react";
import { cn } from "@/lib/utils";
const TABS = [{ seg: "overview", label: "概览" }, { seg: "story", label: "故事" }, { seg: "characters", label: "角色" }, { seg: "scenes", label: "场景" }, { seg: "storyboard", label: "分镜" }, { seg: "assets", label: "素材" }, { seg: "tasks", label: "任务" }] as const;
export function ProjectHeader({ projectId, title }: { projectId: string; title: string; onSave?: () => void; onRun?: () => void }) {
  const pathname = usePathname(); const base = `/freeflow/projects/${projectId}`;
  return <header className="flex shrink-0 flex-col border-b border-border bg-surface"><div className="flex h-14 min-w-0 items-center gap-3 px-4 lg:px-6"><Link href="/freeflow" aria-label="返回项目大厅" className="flex size-9 shrink-0 items-center justify-center rounded-md text-fg-muted transition-colors duration-150 hover:bg-surface-2 hover:text-fg focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-primary"><ChevronLeft aria-hidden className="size-4" /></Link><div className="min-w-0 flex-1"><p className="text-[10px] font-semibold tracking-[0.14em] text-fg-subtle uppercase">项目 / 工作台</p><h1 className="truncate text-sm font-semibold text-fg" title={title}>{title}</h1></div><span className="hidden rounded-full bg-surface-2 px-2 py-1 text-xs text-fg-subtle lg:inline">创作项目</span><Link href={`${base}/settings`} aria-label="项目设置" title="项目设置" className="flex size-9 items-center justify-center rounded-md text-fg-muted hover:bg-surface-2 hover:text-fg focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-primary"><MoreHorizontal aria-hidden className="size-4" /></Link></div><div className="flex h-11 min-w-0 items-center border-t border-border px-3 lg:px-5"><nav aria-label="项目导航" className="flex min-w-0 flex-1 items-center gap-1 overflow-x-auto py-1 [scrollbar-width:thin]">{TABS.map((tab) => { const href = `${base}/${tab.seg}`; const active = pathname === href || pathname.startsWith(`${href}/`); return <Link key={tab.seg} href={href} aria-current={active ? "page" : undefined} className={cn("shrink-0 rounded-md px-3 py-1.5 text-sm transition-colors duration-150 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-primary", active ? "bg-primary-soft font-medium text-primary" : "text-fg-muted hover:bg-surface-2 hover:text-fg")}>{tab.label}</Link>; })}</nav></div></header>;
}
